/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new user
         * @description Creates a new user account and sends an email confirmation link.
         */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/confirm-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Confirm email address
         * @description Validates the confirmation token and marks the user's email as confirmed.
         */
        get: operations["AuthController_confirmEmail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/resend-confirmation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resend confirmation email
         * @description Resends the email confirmation link. No-op if the email is already confirmed or does not exist.
         */
        post: operations["AuthController_resendConfirmation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in
         * @description Authenticates a confirmed user and returns an access + refresh token pair.
         */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh tokens
         * @description Issues a new access + refresh token pair using a valid refresh token.
         */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request password reset
         * @description Sends a password reset email. No-op if the email is not registered.
         */
        post: operations["AuthController_forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset password
         * @description Resets the user password using a valid reset token.
         */
        post: operations["AuthController_resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out
         * @description Revokes all active refresh tokens for the authenticated user.
         */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user
         * @description Returns the authenticated user's profile from the JWT payload.
         */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/channel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the authenticated user channel
         * @description Returns name, nickname and description of the channel owned by the authenticated user.
         */
        get: operations["ChannelsController_getMyChannel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update the authenticated user channel
         * @description Edits nickname, name and description. Changing the nickname changes the public channel URL.
         */
        patch: operations["ChannelsController_updateMyChannel"];
        trace?: never;
    };
    "/videos/{publicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get video status
         * @description Returns the current status and metadata of a video. Only the owning channel can access this endpoint.
         */
        get: operations["VideosController_getVideo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a video
         * @description Edits title, description, category and visibility, replaces the custom thumbnail and publishes or unpublishes the video in a single multipart call. Only the owning channel can access this endpoint.
         */
        patch: operations["VideosController_updateVideo"];
        trace?: never;
    };
    "/videos/{publicId}/public": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a published video for public viewing
         * @description Returns the display metadata of a published video plus two 6 h presigned storage URLs (inline playback and attachment download). Accessible without authentication. A valid bearer token is optional and only identifies the channel owner, who may also read their own drafts.
         */
        get: operations["VideosController_getPublicVideo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{publicId}/view": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a view of a video
         * @description Increments the view counter. Called by the player once per mount, after enough effective playback has accumulated. Accessible without authentication and takes no body. Rate limited to 30 requests per 60 s per IP.
         */
        post: operations["VideosController_registerView"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{publicId}/reaction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Like or dislike a video
         * @description Records or switches the reaction of the authenticated user on the video and returns the like count after the operation. One reaction per user per video; repeating the same reaction changes nothing. There is no public dislike count. Rate limited to 60 requests per 60 s per IP.
         */
        put: operations["VideosController_setReaction"];
        post?: never;
        /**
         * Remove the reaction from a video
         * @description Removes the reaction of the authenticated user and returns the like count after the operation. Idempotent: without a reaction, returns the current state. Rate limited to 60 requests per 60 s per IP.
         */
        delete: operations["VideosController_removeReaction"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{publicId}/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List suggestions for the sidebar of the watch page
         * @description Returns published, public videos from the same category as the reference video, newest first, excluding the reference video itself, drafts and unlisted videos. Paginated with offset/limit; the default page is 4. An empty list is a legitimate result, not an error.
         */
        get: operations["VideosController_getSuggestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{publicId}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream a video
         * @description Redirects to a presigned storage URL for the video file. Accessible without authentication. A valid bearer token is optional and only identifies the channel owner, who may also stream their own drafts.
         */
        get: operations["VideosController_stream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{publicId}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download a video
         * @description Redirects to a presigned storage URL for downloading the video file. Accessible without authentication. A valid bearer token is optional and only identifies the channel owner, who may also download their own drafts.
         */
        get: operations["VideosController_download"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/videos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the videos of the authenticated user channel
         * @description Returns every video of the channel — drafts included — newest first, with offset/limit pagination and the channel total.
         */
        get: operations["ChannelVideosController_listMyVideos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the channels the authenticated user follows
         * @description Returns the followed channels, most recent subscription first, with subscriber count and the count of published, public videos. Paginated with offset/limit; the default page is 50.
         */
        get: operations["ChannelVideosController_listMySubscriptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{nickname}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a public channel
         * @description Returns the public information of a channel. videosCount counts only published, public videos. A valid bearer token is optional and only fills viewerSubscribed.
         */
        get: operations["ChannelVideosController_getPublicChannel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{nickname}/videos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the public videos of a channel
         * @description Returns published, public videos only — drafts and unlisted videos are excluded. Newest published first.
         */
        get: operations["ChannelVideosController_listPublicChannelVideos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{nickname}/subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Subscribe to a channel
         * @description Follows the channel and returns the subscriber count after the operation. Idempotent: subscribing again keeps the count. Rate limited to 60 requests per 60 s per IP.
         */
        put: operations["SubscriptionsController_subscribe"];
        post?: never;
        /**
         * Unsubscribe from a channel
         * @description Stops following the channel and returns the subscriber count after the operation. Idempotent: unsubscribing again keeps the count. Rate limited to 60 requests per 60 s per IP.
         */
        delete: operations["SubscriptionsController_unsubscribe"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{publicId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the comments of a video
         * @description Returns root comments newest first, each with up to 3 preloaded replies and the thread reply count. Paginated with offset/limit; the default page is 10 roots. Accessible without authentication; a valid bearer token only fills viewerReaction.
         */
        get: operations["CommentsController_listComments"];
        put?: never;
        /**
         * Post a comment or a reply
         * @description Creates a root comment, or a reply when parentId is given. Replies are one level deep: replying to a reply attaches the new comment to the same root. Rate limited to 5 requests per 60 s per IP.
         */
        post: operations["CommentsController_createComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/comments/{commentId}/replies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the replies of a comment
         * @description Returns the replies of a root comment beyond the preloaded ones, newest first, with offset/limit pagination. A reply has no replies (one level deep), so asking for them returns an empty page. Accessible without authentication; a valid bearer token only fills viewerReaction.
         */
        get: operations["CommentsController_listReplies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/comments/{commentId}/reaction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Like or dislike a comment
         * @description Records or switches the reaction of the authenticated user on a comment or reply and returns its like count after the operation. One reaction per user per comment. There is no public dislike count. Rate limited to 60 requests per 60 s per IP.
         */
        put: operations["CommentsController_setReaction"];
        post?: never;
        /**
         * Remove the reaction from a comment
         * @description Removes the reaction of the authenticated user from a comment or reply and returns its like count. Idempotent. Rate limited to 60 requests per 60 s per IP.
         */
        delete: operations["CommentsController_removeReaction"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterDto: {
            /** Format: email */
            email: string;
            password: string;
        };
        ResendConfirmationDto: {
            /** Format: email */
            email: string;
        };
        LoginDto: {
            /** Format: email */
            email: string;
            password: string;
        };
        RefreshTokenDto: {
            refresh_token: string;
        };
        ForgotPasswordDto: {
            /** Format: email */
            email: string;
        };
        ResetPasswordDto: {
            token: string;
            new_password: string;
        };
        UpdateChannelDto: {
            /** @description Identidade pública do canal; único e global no sistema. */
            nickname?: string;
            /** @description Nome exibido do canal. */
            name?: string;
            /** @description Descrição do canal. String vazia grava null. */
            description?: string;
        };
        SetReactionDto: {
            /**
             * @description Reação do usuário: like ou dislike.
             * @enum {string}
             */
            type: "like" | "dislike";
        };
        CreateCommentDto: {
            /** @description Texto do comentário; aparado nas pontas antes de validar. */
            body: string;
            /**
             * Format: uuid
             * @description Comentário respondido; ausente cria um comentário-raiz.
             */
            parentId?: string;
        };
        ApiErrorEnvelope: {
            /** @example 401 */
            statusCode: number;
            /** @example INVALID_CREDENTIALS */
            error: string;
            /** @example Invalid email or password */
            message: string | string[];
            code?: string | null;
        };
        ChannelResponse: {
            name: string;
            nickname: string;
            description: string | null;
        };
        PublicChannelResponse: {
            name: string;
            nickname: string;
            description: string | null;
            /** @description Conta apenas vídeos publicados e públicos. */
            videosCount: number;
            /** @description Contagem de inscritos (social-interactions/TD-06, desnormalizada). */
            subscribersCount: number;
            /** @description Se quem pede segue o canal; false para o visitante anônimo (social-interactions-anonymous-gate/TD-02). */
            viewerSubscribed: boolean;
        };
        VideoDetailResponse: {
            publicId: string;
            title: string;
            description: string | null;
            /** @enum {string} */
            status: "draft" | "processing" | "ready" | "failed";
            durationSeconds: number | null;
            /** Format: date-time */
            createdAt: string;
            /** @enum {string} */
            category: "Música" | "Jogos" | "Educação" | "Entretenimento" | "Notícias" | "Esportes" | "Tecnologia" | "Outros";
            /** @enum {string} */
            visibility: "public" | "unlisted";
            /**
             * Format: date-time
             * @description Nulo quando o vídeo ainda é rascunho.
             */
            publishedAt: string | null;
            /** @description URL única já resolvida: a thumbnail customizada quando existe, senão a gerada pelo worker. */
            thumbnailUrl: string | null;
        };
        PublicVideoChannel: {
            nickname: string;
            /** @description Nome de exibição do canal. */
            name: string;
        };
        PublicVideoDetailChannel: {
            nickname: string;
            /** @description Nome de exibição do canal. */
            name: string;
            /** @description Contagem de inscritos do canal (social-interactions/TD-06, desnormalizada). */
            subscribersCount: number;
            /** @description Se quem pede segue o canal; false para o visitante anônimo (social-interactions-anonymous-gate/TD-02). */
            viewerSubscribed: boolean;
        };
        /**
         * @description Reação de quem pede; null para o visitante anônimo (social-interactions-anonymous-gate/TD-02).
         * @enum {string}
         */
        ReactionType: "like" | "dislike";
        PublicVideoDetailResponse: {
            publicId: string;
            title: string;
            description: string | null;
            durationSeconds: number | null;
            /** @enum {string} */
            category: "Música" | "Jogos" | "Educação" | "Entretenimento" | "Notícias" | "Esportes" | "Tecnologia" | "Outros";
            /** @enum {string} */
            visibility: "public" | "unlisted";
            /** Format: date-time */
            publishedAt: string | null;
            viewsCount: number;
            /** @description Contagem de likes do vídeo. */
            likesCount: number;
            /** @description Contagem de comentários publicados, raízes e respostas. */
            commentsCount: number;
            /** @description Reação de quem pede; null para o visitante anônimo (social-interactions-anonymous-gate/TD-02). */
            viewerReaction: components["schemas"]["ReactionType"] | null;
            thumbnailUrl: string | null;
            channel: components["schemas"]["PublicVideoDetailChannel"];
            /** @description URL pré-assinada de 6 h entregue inline; consumida pelo src do <video>. */
            streamUrl: string;
            /** @description URL pré-assinada de 6 h sobre a mesma chave, assinada com content-disposition attachment e filename. Vem junto com a página porque o atributo download do HTML é ignorado cross-origin. */
            downloadUrl: string;
        };
        OwnerVideoListItem: {
            publicId: string;
            title: string;
            durationSeconds: number | null;
            thumbnailUrl: string | null;
            /** @enum {string} */
            status: "draft" | "processing" | "ready" | "failed";
            /** @enum {string} */
            visibility: "public" | "unlisted";
            /**
             * Format: date-time
             * @description Nulo quando o vídeo ainda é rascunho.
             */
            publishedAt: string | null;
            /** @enum {string} */
            category: "Música" | "Jogos" | "Educação" | "Entretenimento" | "Notícias" | "Esportes" | "Tecnologia" | "Outros";
            viewsCount: number;
            likesCount: number;
            commentsCount: number;
        };
        OwnerVideosPage: {
            items: components["schemas"]["OwnerVideoListItem"][];
            /** @description Total de vídeos do canal, ignorando a página. */
            total: number;
            offset: number;
            limit: number;
        };
        PublicVideoListItem: {
            publicId: string;
            title: string;
            durationSeconds: number | null;
            thumbnailUrl: string | null;
            viewsCount: number;
            /** Format: date-time */
            publishedAt: string;
        };
        PublicVideosPage: {
            items: components["schemas"]["PublicVideoListItem"][];
            /** @description Total de vídeos publicados e públicos, ignorando a página. */
            total: number;
            offset: number;
            limit: number;
        };
        SuggestedVideoListItem: {
            publicId: string;
            title: string;
            thumbnailUrl: string | null;
            durationSeconds: number | null;
            viewsCount: number;
            /** Format: date-time */
            publishedAt: string;
            channel: components["schemas"]["PublicVideoChannel"];
        };
        SuggestedVideosPage: {
            items: components["schemas"]["SuggestedVideoListItem"][];
            /** @description Total de sugestões elegíveis, ignorando a página. */
            total: number;
        };
        ReactionStateResponse: {
            /** @description Reação do usuário após a operação; null quando não há. */
            viewerReaction: components["schemas"]["ReactionType"] | null;
            /** @description Contagem de likes do alvo após a operação, lida na mesma transação. */
            likesCount: number;
        };
        SubscriptionStateResponse: {
            /** @description Se o usuário segue o canal após a operação. */
            subscribed: boolean;
            /** @description Contagem de inscritos do canal após a operação, lida na mesma transação. */
            subscribersCount: number;
        };
        CommentAuthor: {
            /** @description Nome de exibição do canal de quem comentou. */
            name: string;
            nickname: string;
        };
        CommentResponse: {
            /** Format: uuid */
            id: string;
            /**
             * Format: uuid
             * @description Nulo para comentário-raiz; o id da raiz para resposta (profundidade 1).
             */
            parentId: string | null;
            body: string;
            /** Format: date-time */
            createdAt: string;
            likesCount: number;
            /** @description Reação de quem pede; null para o visitante anônimo. */
            viewerReaction: components["schemas"]["ReactionType"] | null;
            author: components["schemas"]["CommentAuthor"];
        };
        CommentThreadResponse: {
            /** Format: uuid */
            id: string;
            /**
             * Format: uuid
             * @description Nulo para comentário-raiz; o id da raiz para resposta (profundidade 1).
             */
            parentId: string | null;
            body: string;
            /** Format: date-time */
            createdAt: string;
            likesCount: number;
            /** @description Reação de quem pede; null para o visitante anônimo. */
            viewerReaction: components["schemas"]["ReactionType"] | null;
            author: components["schemas"]["CommentAuthor"];
            /** @description Até 3 respostas, das mais recentes para as mais antigas. */
            replies: components["schemas"]["CommentResponse"][];
            /** @description Total de respostas da thread. */
            repliesCount: number;
        };
        CommentsPage: {
            items: components["schemas"]["CommentThreadResponse"][];
            /** @description Total de comentários-raiz do vídeo. */
            total: number;
            offset: number;
            limit: number;
        };
        RepliesPage: {
            items: components["schemas"]["CommentResponse"][];
            /** @description Total de respostas da raiz. */
            total: number;
            offset: number;
            limit: number;
        };
        SubscribedChannel: {
            name: string;
            nickname: string;
            /** @description Contagem de inscritos do canal. */
            subscribersCount: number;
            /** @description Conta apenas vídeos publicados e públicos. */
            videosCount: number;
        };
        SubscribedChannelsPage: {
            items: components["schemas"]["SubscribedChannel"][];
            /** @description Total de canais seguidos. */
            total: number;
            offset: number;
            limit: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            /** @description User registered successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id?: string;
                        /** Format: email */
                        email?: string;
                    };
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Email already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    AuthController_confirmEmail: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Email confirmed successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Invalid or expired confirmation token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    AuthController_resendConfirmation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResendConfirmationDto"];
            };
        };
        responses: {
            /** @description Confirmation email sent (or silently skipped if already confirmed) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        access_token?: string;
                        refresh_token?: string;
                    };
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Invalid email or password */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Email not confirmed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenDto"];
            };
        };
        responses: {
            /** @description Tokens refreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        access_token?: string;
                        refresh_token?: string;
                    };
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Invalid, expired, or reused refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    AuthController_forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordDto"];
            };
        };
        responses: {
            /** @description Reset email sent (or silently skipped if email not found) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    AuthController_resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordDto"];
            };
        };
        responses: {
            /** @description Password reset successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Invalid or expired reset token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        sub?: string;
                        /** Format: email */
                        email?: string;
                    };
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    ChannelsController_getMyChannel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Channel found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelResponse"];
                };
            };
            /** @description The authenticated user has no channel */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    ChannelsController_updateMyChannel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateChannelDto"];
            };
        };
        responses: {
            /** @description Channel updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelResponse"];
                };
            };
            /** @description Validation failed or empty body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description The authenticated user has no channel */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Nickname already belongs to another channel */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    VideosController_getVideo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Video found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoDetailResponse"];
                };
            };
            /** @description Authenticated user does not own the video */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Video not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    VideosController_updateVideo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    title?: string;
                    description?: string | null;
                    /** @enum {string} */
                    category?: "Música" | "Jogos" | "Educação" | "Entretenimento" | "Notícias" | "Esportes" | "Tecnologia" | "Outros";
                    /** @enum {string} */
                    visibility?: "public" | "unlisted";
                    published?: boolean;
                    /** Format: binary */
                    thumbnail?: string;
                };
            };
        };
        responses: {
            /** @description Video updated — same shape as GET /videos/{publicId} */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoDetailResponse"];
                };
            };
            /** @description Validation failed or unsupported thumbnail type */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Authenticated user does not own the video */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Video not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Video is still processing or failed, so it cannot be published */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    VideosController_getPublicVideo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Video found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicVideoDetailResponse"];
                };
            };
            /** @description Video not found, or a draft requested by someone else */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Video is not ready for viewing */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    VideosController_registerView: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description View registered */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Video not found, or a draft requested by someone else */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description More than 30 requests per 60 s from the same IP */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    VideosController_setReaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetReactionDto"];
            };
        };
        responses: {
            /** @description Reaction recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReactionStateResponse"];
                };
            };
            /** @description type missing or not one of like/dislike */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Missing or invalid bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Video not found, or a draft of another channel */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description More than 60 requests per 60 s from the same IP */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    VideosController_removeReaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reaction removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReactionStateResponse"];
                };
            };
            /** @description Missing or invalid bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Video not found, or a draft of another channel */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description More than 60 requests per 60 s from the same IP */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    VideosController_getSuggestions: {
        parameters: {
            query?: {
                /** @description Quantas sugestões pular. */
                offset?: number;
                /** @description Quantas sugestões retornar. */
                limit?: number;
            };
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Suggestions page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestedVideosPage"];
                };
            };
            /** @description offset or limit outside the accepted range */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Reference video not found, or a draft requested by someone else */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    VideosController_stream: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirects to a presigned storage URL */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Video not found, or a draft requested by someone else */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Video is not ready for streaming */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    VideosController_download: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirects to a presigned storage URL (attachment) */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Video not found, or a draft requested by someone else */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Video is not ready for download */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    ChannelVideosController_listMyVideos: {
        parameters: {
            query?: {
                /** @description Quantos vídeos pular. */
                offset?: number;
                /** @description Quantos vídeos retornar (máximo 50). */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of the channel videos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnerVideosPage"];
                };
            };
            /** @description offset or limit out of range */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description The authenticated user has no channel */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    ChannelVideosController_listMySubscriptions: {
        parameters: {
            query?: {
                /** @description Quantos canais pular. */
                offset?: number;
                /** @description Quantos canais retornar (máximo 100). */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Followed channels page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscribedChannelsPage"];
                };
            };
            /** @description offset or limit out of range */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Missing or invalid bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    ChannelVideosController_getPublicChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nickname: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Channel found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicChannelResponse"];
                };
            };
            /** @description Channel not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    ChannelVideosController_listPublicChannelVideos: {
        parameters: {
            query?: {
                /** @description Quantos vídeos pular. */
                offset?: number;
                /** @description Quantos vídeos retornar (máximo 50). */
                limit?: number;
            };
            header?: never;
            path: {
                nickname: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of public videos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicVideosPage"];
                };
            };
            /** @description offset or limit out of range */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Channel not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    SubscriptionsController_subscribe: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nickname: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscribed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionStateResponse"];
                };
            };
            /** @description Missing or invalid bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Channel not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description More than 60 requests per 60 s from the same IP */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    SubscriptionsController_unsubscribe: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nickname: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unsubscribed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionStateResponse"];
                };
            };
            /** @description Missing or invalid bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Channel not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description More than 60 requests per 60 s from the same IP */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    CommentsController_listComments: {
        parameters: {
            query?: {
                /** @description Quantos comentários-raiz pular. */
                offset?: number;
                /** @description Quantos comentários-raiz retornar. */
                limit?: number;
            };
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Comments page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentsPage"];
                };
            };
            /** @description offset or limit outside the accepted range */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Video not found, or a draft of another channel */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    CommentsController_createComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCommentDto"];
            };
        };
        responses: {
            /** @description Comment created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentResponse"];
                };
            };
            /** @description Empty or too long body, or parentId that is not a uuid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Missing or invalid bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Video not found or a draft of another channel, or parent comment not found in this video */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description More than 5 requests per 60 s from the same IP */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    CommentsController_listReplies: {
        parameters: {
            query?: {
                /** @description Quantas respostas pular — o cliente começa em 3, depois das pré-carregadas. */
                offset?: number;
                /** @description Quantas respostas retornar. */
                limit?: number;
            };
            header?: never;
            path: {
                commentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Replies page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepliesPage"];
                };
            };
            /** @description commentId is not a uuid, or offset/limit out of range */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Comment not found, or its video is a draft of another channel */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    CommentsController_setReaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetReactionDto"];
            };
        };
        responses: {
            /** @description Reaction recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReactionStateResponse"];
                };
            };
            /** @description commentId is not a uuid, or type is not like/dislike */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Missing or invalid bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Comment not found, or its video is a draft of another channel */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description More than 60 requests per 60 s from the same IP */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    CommentsController_removeReaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reaction removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReactionStateResponse"];
                };
            };
            /** @description commentId is not a uuid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Missing or invalid bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Comment not found, or its video is a draft of another channel */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description More than 60 requests per 60 s from the same IP */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
}
